<?php

/**
 * @file
 * Contains cookie_based_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cookie_based_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cookie_based_block module.
    case 'help.page.cookie_based_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
